const actionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
    PRODUCT_TO_CART: "PRODUCT_TO_CART",
    PRODUCT_CART_FETCHING: "PRODUCT_CART_FETCHING",
    PRODUCT_CART_INC: "PRODUCT_CART_INC",
    PRODUCT_CART_DEC: "PRODUCT_CART_DEC",
    PRODUCT_CART_REMOVE: "PRODUCT_CART_REMOVE",
};

export default actionTypes;